name: "fpp-to-json Ref Test"

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  fpp-to-json-ref:
    name: Run fpp-to-json on the Ref deployment
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout F´ Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: "Install requirements.txt"
        run: |
          pip3 install -r ./requirements.txt
        shell: bash
      - name: "Generate Ref Deployment"
        working-directory: ./Ref
        run: |
          fprime-util generate
        shell: bash
      - name: "Run fpp-to-json on Ref topology"
        working-directory: ./Ref/Top
        run: |
          DEPENDENCIES=$(fpp-depend ../build-fprime-automatic-native/locs.fpp *.fpp)
          fpp-to-json ${DEPENDENCIES} *.fpp
        shell: bash
